[build]
  command = "npm i && npm run build"
  publish = "build/browser/"
  functions = "lambda" #  netlify-lambda reads this
[functions]
  directory = "functions/"
[[headers]]
    for = "/*"
    [headers.values]
        Access-Control-Allow-Origin = "*"
